name: Run gfortran tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    name: Build
    steps:

      - name: Install Dependencies
        run: |
          sudo apt update -y
          sudo apt install -y build-essential
          sudo apt install -y cmake

      - uses: actions/checkout@v4

      - name: Download Build and Test
        run: |
          ls
          mkdir build
          cd build
          cmake ..
          make
          ctest
