name: Build and Run with Intel OneAPI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Add Intel oneAPI repository
      run: |
        wget -qO- https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB | sudo apt-key add -
        sudo add-apt-repository "deb https://apt.repos.intel.com/oneapi all main"
        sudo apt update
        sudo apt install -y cmake

    - name: Install Intel oneAPI compilers
      run: |
        sudo apt install -y intel-oneapi-compiler-dpcpp-cpp

    - name: Source Intel oneAPI environment
      run: source /opt/intel/oneapi/setvars.sh

    - name: Compile code with ifort
      run: |
        source /opt/intel/oneapi/setvars.sh
        FC=ifort cmake .
        make 
        ctest
