
ame: Build and Run with Intel oneAPI in Docker

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Pull Intel oneAPI Docker image
      run: docker pull intel/oneapi-basekit

    - name: Run Intel oneAPI container and compile code
      run: |
        docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace intel/oneapi-basekit /bin/bash -c "
          source /opt/intel/oneapi/setvars.sh > /dev/null;
          icx --help;
        "
        
